export default {
  extends: ['stylelint-config-standard'],
  rules: {
    'selector-class-pattern': null,
    'custom-property-pattern': null,
    'keyframes-name-pattern': null,
    'font-family-no-missing-generic-family-keyword': null,
    'color-hex-length': null,
    'unit-allowed-list': ['px', '%', 'em', 'rem', 's', 'ms', 'deg', 'vw', 'vh', 'fr'],
    'color-function-alias-notation': null,
    'color-function-notation': null,
    'alpha-value-notation': null,
    'property-no-vendor-prefix': null,
    'value-keyword-case': null,
    'media-feature-range-notation': null,
    'declaration-property-value-no-unknown': null,
    'length-zero-no-unit': null,
    'comment-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'declaration-empty-line-before': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'font-family-name-quotes': null,
    'no-duplicate-selectors': null,
    'no-descending-specificity': null,
    'rule-empty-line-before': null,
    'at-rule-no-unknown': null,
    'declaration-property-value-keyword-no-deprecated': null,
    'media-feature-name-value-no-unknown': null,
  },
};
