apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wasel-web
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: wasel-web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
        - protocol: UDP
          port: 53
