export { C } from '../../utils/wasel-ds';
export { DS } from '../../utils/wasel-ds';
export { TYPE } from '../../utils/wasel-ds';
export { R } from '../../utils/wasel-ds';
export { SH } from '../../utils/wasel-ds';
export { SPACE } from '../../utils/wasel-ds';
export { C as colors } from '../../utils/wasel-ds';
export { TYPE as typography } from '../../utils/wasel-ds';
export { R as radii } from '../../utils/wasel-ds';
export { SH as shadows } from '../../utils/wasel-ds';