export const walletText = {
  en: {
    walletTitle: 'Wasel Wallet',
    balance: 'Available Balance',
    pending: 'Pending',
    rewards: 'Rewards',
    hideBalance: 'Hide balance',
    showBalance: 'Show balance',
    addMoney: 'Add Money',
    withdraw: 'Withdraw',
    sendMoney: 'Send',
    overview: 'Overview',
    transactions: 'Transactions',
    send: 'Send',
    rewardsTab: 'Rewards',
    insights: 'Insights',
    settings: 'Settings',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    noTransactions: 'Transactions will appear here as soon as your wallet becomes active',
    quickActions: 'Core Actions',
    topUpAmount: 'Top-up Amount (JOD)',
    paymentMethod: 'Payment Method',
    card: 'Credit/Debit Card',
    applePay: 'Apple Pay',
    bankTransfer: 'Bank Transfer',
    cliq: 'CliQ',
    topUp: 'Top Up',
    withdrawAmount: 'Withdrawal Amount (JOD)',
    bankAccount: 'Bank Account / IBAN',
    instant: 'Instant',
    standard: 'Standard (1-3 days)',
    confirmWithdraw: 'Withdraw',
    recipientId: 'Recipient User ID',
    sendAmount: 'Amount (JOD)',
    noteOptional: 'Note (optional)',
    confirmSend: 'Send Money',
    activeRewards: 'Active Rewards',
    claimedRewards: 'Claimed Rewards',
    claim: 'Claim',
    expires: 'Expires',
    noRewards: 'No rewards available',
    spendingInsights: 'Spending Insights',
    thisMonth: 'This Month',
    vsLastMonth: 'vs last month',
    earned: 'Earned',
    spent: 'Spent',
    monthlyTrend: 'Monthly Trend',
    categoryBreakdown: 'Category Breakdown',
    securityPin: 'Wallet PIN',
    setPin: 'Set PIN',
    changePin: 'Change PIN',
    pinDescription: 'Protect transactions with a 4-digit PIN',
    autoTopUp: 'Auto Top-Up',
    autoTopUpDesc: 'Automatically add funds when balance drops below threshold',
    threshold: 'Threshold (JOD)',
    topUpAmountSetting: 'Top-up Amount (JOD)',
    subscription: 'Wasel Plus',
    subscribeNow: 'Subscribe Now',
    activeSubscription: 'Active Subscription',
    escrow: 'Active Escrows',
    held: 'Held',
    processing: 'Processing...',
    pinDigits: 'Enter 4-digit PIN',
    carbonSaved: 'CO2 Saved',
    totalTx: 'Total Transactions',
    jod: 'JOD',
  },
  ar: {
    walletTitle: 'محفظة واصل',
    balance: 'الرصيد المتاح',
    pending: 'معلّق',
    rewards: 'المكافآت',
    hideBalance: 'إخفاء الرصيد',
    showBalance: 'إظهار الرصيد',
    addMoney: 'إضافة رصيد',
    withdraw: 'سحب',
    sendMoney: 'إرسال',
    overview: 'نظرة عامة',
    transactions: 'المعاملات',
    send: 'إرسال',
    rewardsTab: 'مكافآت',
    insights: 'تحليلات',
    settings: 'الإعدادات',
    recentTransactions: 'آخر المعاملات',
    viewAll: 'عرض الكل',
    noTransactions: 'لا يوجد معاملات بعد',
    quickActions: 'إجراءات سريعة',
    topUpAmount: 'مبلغ الشحن (دينار)',
    paymentMethod: 'طريقة الدفع',
    card: 'بطاقة ائتمان',
    applePay: 'Apple Pay',
    bankTransfer: 'تحويل بنكي',
    cliq: 'كليك',
    topUp: 'شحن',
    withdrawAmount: 'مبلغ السحب (دينار)',
    bankAccount: 'حساب البنك / IBAN',
    instant: 'فوري',
    standard: 'عادي (1-3 أيام)',
    confirmWithdraw: 'سحب',
    recipientId: 'معرّف المستلم',
    sendAmount: 'المبلغ (دينار)',
    noteOptional: 'ملاحظة (اختياري)',
    confirmSend: 'إرسال المال',
    activeRewards: 'مكافآت نشطة',
    claimedRewards: 'مكافآت مستلمة',
    claim: 'استلام',
    expires: 'ينتهي',
    noRewards: 'لا توجد مكافآت',
    spendingInsights: 'تحليلات الإنفاق',
    thisMonth: 'هذا الشهر',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    earned: 'ربح',
    spent: 'إنفاق',
    monthlyTrend: 'الاتجاه الشهري',
    categoryBreakdown: 'تفصيل حسب الفئة',
    securityPin: 'رمز PIN للمحفظة',
    setPin: 'تعيين PIN',
    changePin: 'تغيير PIN',
    pinDescription: 'احمِ معاملاتك برمز من 4 أرقام',
    autoTopUp: 'شحن تلقائي',
    autoTopUpDesc: 'شحن الرصيد تلقائيا عند انخفاضه',
    threshold: 'الحد الأدنى (دينار)',
    topUpAmountSetting: 'مبلغ الشحن (دينار)',
    subscription: 'واصل بلس',
    subscribeNow: 'اشترك الآن',
    activeSubscription: 'اشتراك فعّال',
    escrow: 'ضمانات نشطة',
    held: 'محجوز',
    processing: 'جاري المعالجة...',
    pinDigits: 'أدخل رمز من 4 أرقام',
    carbonSaved: 'CO2 موفّر',
    totalTx: 'إجمالي المعاملات',
    jod: 'دينار',
  },
} as const;
