export const walletText = {
  en: {
    walletTitle: 'Wasel Wallet',
    balance: 'Available Balance',
    pending: 'Pending',
    rewards: 'Rewards',
    hideBalance: 'Hide balance',
    showBalance: 'Show balance',
    addMoney: 'Add Money',
    withdraw: 'Withdraw',
    sendMoney: 'Send',
    overview: 'Overview',
    transactions: 'Transactions',
    send: 'Send',
    rewardsTab: 'Rewards',
    insights: 'Insights',
    settings: 'Settings',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    noTransactions: 'No transactions',
    quickActions: 'Core Actions',
    topUpAmount: 'Top-up Amount (JOD)',
    paymentMethod: 'Payment Method',
    card: 'Credit/Debit Card',
    applePay: 'Apple Pay',
    bankTransfer: 'Bank Transfer',
    cliq: 'CliQ',
    topUp: 'Top Up',
    withdrawAmount: 'Withdrawal Amount (JOD)',
    bankAccount: 'Bank Account / IBAN',
    instant: 'Instant',
    standard: 'Standard (1-3 days)',
    confirmWithdraw: 'Withdraw',
    recipientId: 'Recipient User ID',
    sendAmount: 'Amount (JOD)',
    noteOptional: 'Note (optional)',
    confirmSend: 'Send Money',
    activeRewards: 'Active Rewards',
    claimedRewards: 'Claimed Rewards',
    claim: 'Claim',
    expires: 'Expires',
    noRewards: 'No rewards',
    spendingInsights: 'Spending Insights',
    thisMonth: 'This Month',
    vsLastMonth: 'vs last month',
    earned: 'Earned',
    spent: 'Spent',
    monthlyTrend: 'Monthly Trend',
    categoryBreakdown: 'Category Breakdown',
    securityPin: 'Wallet PIN',
    setPin: 'Set PIN',
    changePin: 'Change PIN',
    pinDescription: 'Protect transactions with a 4-digit PIN',
    autoTopUp: 'Auto Top-Up',
    autoTopUpDesc: 'Automatically add funds when balance drops below threshold',
    threshold: 'Threshold (JOD)',
    topUpAmountSetting: 'Top-up Amount (JOD)',
    subscription: 'Wasel Plus',
    subscribeNow: 'Subscribe Now',
    activeSubscription: 'Active Subscription',
    escrow: 'Active Escrows',
    held: 'Held',
    processing: 'Processing...',
    pinDigits: 'Enter 4-digit PIN',
    carbonSaved: 'CO2 Saved',
    totalTx: 'Total Transactions',
    jod: 'JOD',
    liveStatus: 'Live',
    walletSubtitle: 'Balance and payments',
    redirectingToSignIn: 'Redirecting to sign in...',
    walletUnavailableTitle: 'Wallet coming soon',
    walletUnavailableDescription: 'Payments are still being enabled.',
    walletUnavailableHint: 'Setup in progress',
    walletReadOnlyTitle: 'Wallet is read-only right now',
    walletReadOnlyDescription: 'Balances and history stay visible, but wallet actions are paused until the secure payment service reconnects.',
    walletReadOnlyHint: 'Top-ups, withdrawals, transfers, rewards, subscriptions, and PIN changes will reopen automatically.',
    walletReadOnlyToast: 'Wallet actions are paused until the secure payment service reconnects.',
    rewardsEmptyHint: 'Earn rewards from trips',
    availableLabel: 'Available',
    freeLabel: 'Free',
    userIdPlaceholder: 'User ID',
    notePlaceholder: 'Note...',
    maskedBalance: '******',
    maskedShort: '**',
    maskedPin: '****',
    activeLabel: 'Active',
    invalidAmount: 'Enter a valid amount',
    enterBankAccount: 'Enter bank account',
    insufficientBalance: 'Insufficient balance',
    enterRecipientId: 'Enter recipient ID',
    pinMustBeFourDigits: 'PIN must be 4 digits',
    walletLoadError: 'Unable to load wallet right now',
    walletEmptyTitle: 'Wallet data is temporarily unavailable',
    walletEmptyDescription: 'We could not load your latest balance yet. Retry to reconnect the wallet service and restore the most recent snapshot.',
    walletEmptyAction: 'Fresh wallet sync',
    walletSnapshotLabel: 'Latest snapshot',
    walletSnapshotDescription: 'Balances stay protected and no wallet action will be attempted until data is back.',
    retry: 'Retry',
    refreshed: 'Refreshed',
    autoTopUpEnabledToast: 'Auto top-up enabled',
    autoTopUpDisabledToast: 'Auto top-up disabled',
    welcomeToPlus: 'Welcome to Wasel Plus!',
    rewardClaimed: 'Reward claimed!',
    pinSetSuccess: 'PIN set successfully',
    heroSubtitle: 'Add, send, or withdraw in one place.',
    topUpSuccess: 'JOD {amount} added successfully',
    withdrawSuccess: 'JOD {amount} withdrawn successfully',
    sendSuccess: 'JOD {amount} sent',
    txStatusPending: 'Pending',
    txStatusProcessing: 'Processing',
    txStatusAuthorized: 'Authorized',
    txStatusPosted: 'Posted',
    txStatusCompleted: 'Completed',
    txStatusCaptured: 'Captured',
    txStatusRefunded: 'Refunded',
    txStatusFailed: 'Failed',
    totalDeposited: 'Deposited',
    totalSpentLabel: 'Spent',
    totalEarnedLabel: 'Earned',
    inSettlement: 'In settlement',
    needsFollowUp: 'Needs follow-up',
    settlementReadiness: 'Settlement readiness',
    currencyLabel: 'Currency',
    walletTypeLabel: 'Wallet Type',
    createdLabel: 'Created',
    total: 'Total',
  },
  ar: {
    walletTitle: 'محفظة واصل',
    balance: 'الرصيد المتاح',
    pending: 'معلق',
    rewards: 'المكافآت',
    hideBalance: 'إخفاء الرصيد',
    showBalance: 'إظهار الرصيد',
    addMoney: 'إضافة رصيد',
    withdraw: 'سحب',
    sendMoney: 'إرسال',
    overview: 'نظرة عامة',
    transactions: 'المعاملات',
    send: 'إرسال',
    rewardsTab: 'المكافآت',
    insights: 'التحليلات',
    settings: 'الإعدادات',
    recentTransactions: 'آخر المعاملات',
    viewAll: 'عرض الكل',
    noTransactions: 'ستظهر المعاملات هنا فور تفعيل المحفظة',
    quickActions: 'الإجراءات الأساسية',
    topUpAmount: 'مبلغ الشحن (دينار)',
    paymentMethod: 'طريقة الدفع',
    card: 'بطاقة ائتمان أو خصم',
    applePay: 'أبل باي',
    bankTransfer: 'تحويل بنكي',
    cliq: 'كليك',
    topUp: 'شحن',
    withdrawAmount: 'مبلغ السحب (دينار)',
    bankAccount: 'الحساب البنكي / IBAN',
    instant: 'فوري',
    standard: 'عادي (1-3 أيام)',
    confirmWithdraw: 'سحب',
    recipientId: 'معرف المستلم',
    sendAmount: 'المبلغ (دينار)',
    noteOptional: 'ملاحظة (اختياري)',
    confirmSend: 'إرسال المال',
    activeRewards: 'المكافآت النشطة',
    claimedRewards: 'المكافآت المستلمة',
    claim: 'استلام',
    expires: 'ينتهي',
    noRewards: 'لا توجد مكافآت متاحة',
    spendingInsights: 'تحليلات الإنفاق',
    thisMonth: 'هذا الشهر',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    earned: 'المكتسب',
    spent: 'المنفق',
    monthlyTrend: 'الاتجاه الشهري',
    categoryBreakdown: 'التفصيل حسب الفئة',
    securityPin: 'رمز PIN للمحفظة',
    setPin: 'تعيين PIN',
    changePin: 'تغيير PIN',
    pinDescription: 'احم معاملاتك برمز من 4 أرقام',
    autoTopUp: 'شحن تلقائي',
    autoTopUpDesc: 'أضف رصيداً تلقائياً عندما ينخفض الرصيد عن الحد المحدد',
    threshold: 'الحد الأدنى (دينار)',
    topUpAmountSetting: 'مبلغ الشحن (دينار)',
    subscription: 'واصل بلس',
    subscribeNow: 'اشترك الآن',
    activeSubscription: 'اشتراك فعال',
    escrow: 'عمليات الضمان النشطة',
    held: 'محجوز',
    processing: 'جارٍ المعالجة...',
    pinDigits: 'أدخل رمزاً من 4 أرقام',
    carbonSaved: 'انبعاثات CO2 التي تم توفيرها',
    totalTx: 'إجمالي المعاملات',
    jod: 'دينار',
    liveStatus: 'نشط',
    walletSubtitle: 'المدفوعات والرصيد والمكافآت',
    redirectingToSignIn: 'جارٍ تحويلك إلى تسجيل الدخول...',
    walletUnavailableTitle: 'المحفظة قيد الإطلاق',
    walletUnavailableDescription: 'نجهز تدفق المدفوعات والأمان والتسوية. أكمل إعداد الخلفية لرؤية تجربة المحفظة الكاملة.',
    walletUnavailableHint: 'تجربة مالية أكثر تنسيقاً قريباً',
    walletReadOnlyTitle: 'المحفظة في وضع القراءة فقط حالياً',
    walletReadOnlyDescription: 'يبقى الرصيد والسجل ظاهرين، لكن إجراءات المحفظة متوقفة حتى يعود مسار الدفع الآمن للعمل.',
    walletReadOnlyHint: 'سيعود الشحن والسحب والتحويل والمكافآت والاشتراك وPIN تلقائياً عند تعافي خدمة المدفوعات.',
    walletReadOnlyToast: 'إجراءات المحفظة متوقفة حتى يعود مسار الدفع الآمن للعمل.',
    rewardsEmptyHint: 'أكمل رحلات لربح مكافآت',
    availableLabel: 'الرصيد المتاح',
    freeLabel: 'مجاني',
    userIdPlaceholder: 'معرف المستلم',
    notePlaceholder: 'ملاحظة...',
    maskedBalance: '******',
    maskedShort: '**',
    maskedPin: '****',
    activeLabel: 'نشط',
    invalidAmount: 'أدخل مبلغاً صحيحاً',
    enterBankAccount: 'أدخل رقم الحساب',
    insufficientBalance: 'الرصيد غير كافٍ',
    enterRecipientId: 'أدخل معرف المستلم',
    pinMustBeFourDigits: 'الرمز يجب أن يكون 4 أرقام',
    walletLoadError: 'تعذر تحميل المحفظة الآن',
    walletEmptyTitle: 'بيانات المحفظة غير متاحة مؤقتاً',
    walletEmptyDescription: 'لم نتمكن من جلب آخر رصيد الآن. أعد المحاولة لإعادة ربط خدمة المحفظة وإظهار أحدث لقطة آمنة.',
    walletEmptyAction: 'مزامنة محفظة جديدة',
    walletSnapshotLabel: 'آخر لقطة',
    walletSnapshotDescription: 'الرصيد يبقى محمياً ولن يتم تنفيذ أي إجراء حتى تعود البيانات.',
    retry: 'أعد المحاولة',
    refreshed: 'تم التحديث',
    autoTopUpEnabledToast: 'تم تفعيل الشحن التلقائي',
    autoTopUpDisabledToast: 'تم إيقاف الشحن التلقائي',
    welcomeToPlus: 'مبروك! تم الاشتراك في واصل بلس',
    rewardClaimed: 'تم استلام المكافأة!',
    pinSetSuccess: 'تم تعيين PIN بنجاح',
    heroSubtitle: 'أضف أو أرسل أو اسحب في مكان واحد.',
    topUpSuccess: 'تمت إضافة {amount} دينار بنجاح',
    withdrawSuccess: 'تم سحب {amount} دينار بنجاح',
    sendSuccess: 'تم إرسال {amount} دينار',
    txStatusPending: 'معلق',
    txStatusProcessing: 'جارٍ المعالجة',
    txStatusAuthorized: 'مُعتمد',
    txStatusPosted: 'مُسجَّل',
    txStatusCompleted: 'مكتمل',
    txStatusCaptured: 'محصَّل',
    txStatusRefunded: 'مُستردّ',
    txStatusFailed: 'فاشل',
    totalDeposited: 'إجمالي الإيداع',
    totalSpentLabel: 'إجمالي الإنفاق',
    totalEarnedLabel: 'إجمالي الربح',
    inSettlement: 'التحويلات قيد المعالجة',
    needsFollowUp: 'حالات تحتاج متابعة',
    settlementReadiness: 'جاهزية السداد',
    currencyLabel: 'العملة',
    walletTypeLabel: 'نوع المحفظة',
    createdLabel: 'تاريخ الإنشاء',
    total: 'الإجمالي',
  },
} as const;
