declare module 'react-router' {
  export * from 'react-router-dom';
}

declare module 'react-router-dom' {
  import { ReactNode } from 'react';
  export function useLocation(): { pathname: string; search: string; hash: string; state: unknown };
  export function useNavigate(): (to: string | number, options?: { replace?: boolean; state?: unknown }) => void;
  export function useSearchParams(): [URLSearchParams, (params: URLSearchParams | string, options?: { replace?: boolean; state?: unknown }) => void];
  export function createBrowserRouter(routes: unknown[]): unknown;
  export function isRouteErrorResponse(error: unknown): boolean;
  export function useRouteError(): unknown;
  export function Navigate(to: string | number, options?: { replace?: boolean; state?: unknown }): null;
  export function Outlet(): ReactNode;
  export function Link(props: { to: string; children: ReactNode; [key: string]: unknown }): null;
  export function NavLink(props: { to: string; children: ReactNode; [key: string]: unknown }): null;
  export function Form(props: { action?: string; method?: string; children: ReactNode; [key: string]: unknown }): null;
  export function ScrollRestoration(): null;
  export function BrowserRouter(props: { children: ReactNode }): ReactNode;
  export function HashRouter(props: { children: ReactNode }): ReactNode;
  export function MemoryRouter(props: { children: ReactNode; initialEntries?: string[] }): ReactNode;
  export function Routes(props: { children: ReactNode }): ReactNode;
  export function Route(props: { path?: string; index?: boolean; caseSensitive?: boolean; element?: ReactNode }): null;
  export function RouteObject: unknown;
}

declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  export interface LucideIcon extends FC<SVGProps<SVGSVGElement>> {}
  export const Icon: LucideIcon;
  export const LucideIcon: LucideIcon;
  export const Activity: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const ArrowDownLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const BadgeDollarSign: LucideIcon;
  export const Bell: LucideIcon;
  export const Brain: LucideIcon;
  export const Briefcase: LucideIcon;
  export const Bus: LucideIcon;
  export const Calendar: LucideIcon;
  export const Car: LucideIcon;
  export const CarFront: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Clock: LucideIcon;
  export const Crown: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const FileText: LucideIcon;
  export const Gauge: LucideIcon;
  export const Globe: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const Headphones: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const Key: LucideIcon;
  export const Landmark: LucideIcon;
  export const LifeBuoy: LucideIcon;
  export const LineChart: LucideIcon;
  export const LoaderCircle: LucideIcon;
  export const Lock: LucideIcon;
  export const LogOut: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const Monitor: LucideIcon;
  export const Navigation: LucideIcon;
  export const Navigation2: LucideIcon;
  export const Network: LucideIcon;
  export const Package: LucideIcon;
  export const PackageCheck: LucideIcon;
  export const Pause: LucideIcon;
  export const Phone: LucideIcon;
  export const Play: LucideIcon;
  export const Plus: LucideIcon;
  export const QrCode: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Route: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const Search: LucideIcon;
  export const SearchX: LucideIcon;
  export const Send: LucideIcon;
  export const Settings: LucideIcon;
  export const Shield: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Siren: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Star: LucideIcon;
  export const TimerReset: LucideIcon;
  export const Trash2: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const UserCheck: LucideIcon;
  export const UserCircle2: LucideIcon;
  export const UserRound: LucideIcon;
  export const Users: LucideIcon;
  export const Wallet: LucideIcon;
  export const X: LucideIcon;
  export const XCircle: LucideIcon;
  export const Zap: LucideIcon;
  export const Boxes: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const Ticket: LucideIcon;
  export const ArrowUpRight as ArrowUpRightIcon: LucideIcon;
  export const ArrowDownLeft as ArrowDownLeftIcon: LucideIcon;
  export const TrendingUp as TrendingUpIcon: LucideIcon;
  export const TrendingDown as TrendingDownIcon: LucideIcon;
  export const LucideIcon as default: LucideIcon;
}

declare module 'framer-motion' {
  export const motion: Record<string, unknown>;
  export const AnimatePresence: unknown;
  export const useMotionValue: unknown;
  export const useTransform: unknown;
  export const useSpring: unknown;
  export const useScroll: unknown;
  export const useInView: unknown;
  export const useAnimation: unknown;
  export const useMotionValueEvent: unknown;
  export const useReducedMotion: unknown;
  export const useDragControls: unknown;
  export const useVelocity: unknown;
  export const useTime: unknown;
  export const useVector: unknown;
  export const useAccelerometer: unknown;
  export const useDeviceOrientation: unknown;
  export const useDeviceMotion: unknown;
  export const useScrollProgress: unknown;
  export const useElementSize: unknown;
  export const useElementBounding: unknown;
  export const useViewportScroll: unknown;
  export const useViewportSize: unknown;
  export const useViewportBounding: unknown;
  export const useViewportElement: unknown;
  export const useViewportProgress: unknown;
  export const useViewportInView: unknown;
  export const useViewportMotionValue: unknown;
  export const useViewportTransform: unknown;
  export const useViewportSpring: unknown;
  export const useViewportScrollProgress: unknown;
  export const useViewportBoundingClientRect: unknown;
  export const useViewportElementSize: unknown;
  export const useViewportElementBounding: unknown;
  export const useViewportElementScroll: unknown;
  export const useViewportElementInView: unknown;
  export const useViewportElementMotionValue: unknown;
  export const useViewportElementTransform: unknown;
  export const useViewportElementSpring: unknown;
  export const useViewportElementScrollProgress: unknown;
  export const useViewportElementBoundingClientRect: unknown;
  export const useViewportElementSizeObserver: unknown;
  export const useViewportElementBoundingObserver: unknown;
  export const useViewportElementScrollObserver: unknown;
  export const useViewportElementInViewObserver: unknown;
  export const useViewportElementMotionValueObserver: unknown;
  export const useViewportElementTransformObserver: unknown;
  export const useViewportElementSpringObserver: unknown;
  export const useViewportElementScrollProgressObserver: unknown;
  export const useViewportElementBoundingClientRectObserver: unknown;
}

declare module 'zod' {
  export const z: unknown;
  export default z;
}

declare module '@supabase/auth-js' {
  export const SupabaseAuthClient: unknown;
  export const AuthChangeEvent: unknown;
  export default SupabaseAuthClient;
}

declare module '@microsoft/applicationinsights-web' {
  export const applicationInsights: unknown;
  export const DistributedTracingModes: unknown;
  export default applicationInsights;
}

declare module '@tanstack/react-query' {
  export const QueryClient: unknown;
  export const QueryCache: unknown;
  export const MutationCache: unknown;
  export const useQueryClient: unknown;
  export const useQuery: unknown;
  export const useMutation: unknown;
  export const useQueries: unknown;
  export const useInfiniteQuery: unknown;
  export const useIsFetching: unknown;
  export const useIsMutating: unknown;
  export const usePrefetchQuery: unknown;
  export const usePrefetchInfiniteQuery: unknown;
  export const QueryClientProvider: unknown;
  export const MutationCache: unknown;
  export const QueryCache: unknown;
  export const DehydratedState: unknown;
  export const Hydrate: unknown;
  export const focusManager: unknown;
  export const onlineManager: unknown;
  export const QueryObserver: unknown;
  export const MutationObserver: unknown;
  export const InfiniteQueryObserver: unknown;
  export const QueriesObserver: unknown;
  export const NotifyManager: unknown;
  export const console: unknown;
  export const hydrationErrorInfo: unknown;
  export const noop: unknown;
  export const fetchOptimistic: unknown;
  export const defaultKey: unknown;
  export const replaceEqualDeep: unknown;
  export const stableHash: unknown;
  export const hashKey: unknown;
  export const isEqual: unknown;
  export const isDev: unknown;
  export const time: unknown;
  export const functionalUpdate: unknown;
  export const getVerboseLogs: unknown;
  export const setVerboseLogs: unknown;
  export const getLogger: unknown;
  export const setLogger: unknown;
  export const Context: unknown;
  export const useBaseQuery: unknown;
  export const useBaseMutation: unknown;
  export const useQuerySubscriber: unknown;
  export const useMutationSubscriber: unknown;
  export const useQueryClient: unknown;
  export const useIsFetching: unknown;
  export const useIsMutating: unknown;
  export const usePrefetchQuery: unknown;
  export const usePrefetchInfiniteQuery: unknown;
  export const QueryClientProvider: unknown;
  export const MutationCache: unknown;
  export const QueryCache: unknown;
  export const DehydratedState: unknown;
  export const Hydrate: unknown;
  export const focusManager: unknown;
  export const onlineManager: unknown;
  export const QueryObserver: unknown;
  export const MutationObserver: unknown;
  export const InfiniteQueryObserver: unknown;
  export const QueriesObserver: unknown;
  export const NotifyManager: unknown;
  export const console: unknown;
  export const hydrationErrorInfo: unknown;
  export const noop: unknown;
  export const fetchOptimistic: unknown;
  export const defaultKey: unknown;
  export const replaceEqualDeep: unknown;
  export const stableHash: unknown;
  export const hashKey: unknown;
  export const isEqual: unknown;
  export const isDev: unknown;
  export const time: unknown;
  export const functionalUpdate: unknown;
  export const getVerboseLogs: unknown;
  export const setVerboseLogs: unknown;
  export const getLogger: unknown;
  export const setLogger: unknown;
  export const Context: unknown;
  export const useBaseQuery: unknown;
  export const useBaseMutation: unknown;
  export const useQuerySubscriber: unknown;
  export const useMutationSubscriber: unknown;
  export default QueryClient;
}

declare module '@sentry/react' {
  export const init: unknown;
  export const browserTracingIntegration: unknown;
  export const replayIntegration: unknown;
  export const default: unknown;
  export const reactErrorHandler: unknown;
  export const wrapUseRoutesV7: unknown;
}
