import type { SupportedCurrency, CurrencyConfig } from './types';
export { SUPPORTED_CURRENCY_CODES, PLATFORM_CURRENCY } from './types';

export const CURRENCIES: Record<SupportedCurrency, CurrencyConfig> = {
  JOD: {
    code: 'JOD',
    symbol: 'د.أ',
    name: 'Jordanian Dinar',
    nameAr: 'الدينار الأردني',
    locale: 'ar-JO',
    decimals: 3,
    minFare: 0.5,
  },
  USD: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    nameAr: 'دولار أمريكي',
    locale: 'en-US',
    decimals: 2,
    minFare: 0.7,
  },
  EUR: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    nameAr: 'يورو',
    locale: 'de-DE',
    decimals: 2,
    minFare: 0.65,
  },
  GBP: {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound',
    nameAr: 'جنيه إسترليني',
    locale: 'en-GB',
    decimals: 2,
    minFare: 0.55,
  },
  AED: {
    code: 'AED',
    symbol: 'د.إ',
    name: 'UAE Dirham',
    nameAr: 'درهم إماراتي',
    locale: 'ar-AE',
    decimals: 2,
    minFare: 2.5,
  },
  SAR: {
    code: 'SAR',
    symbol: 'ر.س',
    name: 'Saudi Riyal',
    nameAr: 'ريال سعودي',
    locale: 'ar-SA',
    decimals: 2,
    minFare: 2.5,
  },
  EGP: {
    code: 'EGP',
    symbol: 'ج.م',
    name: 'Egyptian Pound',
    nameAr: 'جنيه مصري',
    locale: 'ar-EG',
    decimals: 2,
    minFare: 20,
  },
  KWD: {
    code: 'KWD',
    symbol: 'د.ك',
    name: 'Kuwaiti Dinar',
    nameAr: 'دينار كويتي',
    locale: 'ar-KW',
    decimals: 3,
    minFare: 0.15,
  },
  BHD: {
    code: 'BHD',
    symbol: 'د.ب',
    name: 'Bahraini Dinar',
    nameAr: 'دينار بحريني',
    locale: 'ar-BH',
    decimals: 3,
    minFare: 0.18,
  },
  QAR: {
    code: 'QAR',
    symbol: 'ر.ق',
    name: 'Qatari Riyal',
    nameAr: 'ريال قطري',
    locale: 'ar-QA',
    decimals: 2,
    minFare: 2.5,
  },
  OMR: {
    code: 'OMR',
    symbol: 'ر.ع',
    name: 'Omani Rial',
    nameAr: 'ريال عُماني',
    locale: 'ar-OM',
    decimals: 3,
    minFare: 0.2,
  },
  MAD: {
    code: 'MAD',
    symbol: 'د.م',
    name: 'Moroccan Dirham',
    nameAr: 'درهم مغربي',
    locale: 'ar-MA',
    decimals: 2,
    minFare: 8,
  },
  TND: {
    code: 'TND',
    symbol: 'د.ت',
    name: 'Tunisian Dinar',
    nameAr: 'دينار تونسي',
    locale: 'ar-TN',
    decimals: 3,
    minFare: 1.5,
  },
  IQD: {
    code: 'IQD',
    symbol: 'ع.د',
    name: 'Iraqi Dinar',
    nameAr: 'دينار عراقي',
    locale: 'ar-IQ',
    decimals: 0,
    minFare: 1000,
  },
};

// Exchange rates (base: JOD)
// In production, these should be refreshed from a live exchange-rate API
// (e.g., exchangerate-api.com) at least once per hour.

export const EXCHANGE_RATES_FROM_JOD: Record<SupportedCurrency, number> = {
  JOD: 1.0,
  USD: 1.41,
  EUR: 1.3,
  GBP: 1.115,
  AED: 5.18,
  SAR: 5.29,
  EGP: 68.5,
  KWD: 0.435,
  BHD: 0.531,
  QAR: 5.15,
  OMR: 0.545,
  MAD: 14.1,
  TND: 4.35,
  IQD: 1850,
};

