apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasel-web
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
